### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by pribadihcr** [mosheliv/tensortrt-yolo-python-api#1]
Hi @mosheliv,

Look like the step no 6 for the link is wrong for deepstream_reference_apps/yolo/apps/trt-yolo/CMakeFiles/trt-yolo-app.dir/flags.make, should it deepstream_reference_apps/yolo/apps/trt-yolo/build/CMakeFiles/trt-yolo-app.dir/flags.make ?

**Comment by mosheliv** [comment]
you might be right. I'll retry it from a clean install.

**Comment by mosheliv** [comment]
fixed
