### ISSUE TITLE
no lib folder

### ISSUE THREAD

**Issue by pribadihcr** [mosheliv/tensortrt-yolo-python-api#2]
Hi @mosheliv,

In step 9 cd apps/trt-yolo/lib.  in my case, there is lib folder. It exist in apps/trt-yolo/build/lib or https://github.com/NVIDIA-AI-IOT/deepstream_reference_apps/tree/master/yolo/lib . so which lib did you mean?

**Comment by mosheliv** [comment]
seems like i skipped the cd build in my setup, I think.

**Comment by mosheliv** [comment]
fixed the readme. please delete the deepstream directory and reclone it
