### ISSUE TITLE
error with libyolo.so

### ISSUE THREAD

**Issue by IbrahimBond** [mosheliv/tensortrt-yolo-python-api#4]
hi mosh, 

thanks for creating this awesome wrapper. i am having the following trouble running it though: 

Traceback (most recent call last):
  File "t.py", line 7, in <module>
    lib=CDLL('./libyolo.so')
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./libyolo.so: undefined symbol: _ZN2cv7putTextERKNS_17_InputOutputArrayERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_6Point_IiEEidNS_7Scalar_IdEEiib

do you have an idea of what could e the cause. 

i am also wondering if it could run on a video?

thanks

**Comment by mosheliv** [comment]
It looks like you don't have opencv installed?
Yes, you can run it on video, its fast enough. You should also check out the more mature mobilenet-ssd implementation that was posted on the forum. If you can't find it, I'll look it up for you

**Comment by IbrahimBond** [comment]
thanks for your response. i do have opencv 3.4.6 installed :/

what about the mobilenet-ssd? is it a faster implementation? i will go have a look

**Comment by IbrahimBond** [comment]
hi mosh i am still having the same issue. could you tell me what version of opencv do you use?  what version of g++ also?

**Comment by mosheliv** [comment]
I think i have 4 installed now but ut shouldn't matrer....

Try deleting the repository and reinstalling from scratch. Cmake is notorious for caching things

**Comment by IbrahimBond** [comment]
its weird i have, i have reinstalled twice before and gave the same error, anyway this time it worked, thanks for your response. 

now i am having this error though:
Traceback (most recent call last):
  File "t.py", line 33, in <module>
    for tt in ret_buf.value.split("|"):
TypeError: a bytes-like object is required, not 'str'

do you have any idea?

**Comment by mosheliv** [comment]
Sigh. I remember getting this error but not why...
Ah wait was something to do with the open mode of the file? Mmmm
I really recommend the mobilenet-ssd vesion. Its better. I'll try looking
at it next week.

**Comment by IbrahimBond** [comment]
hi mosh, 

i have tried running it in python 2 and it worked. do you know what i need to change to make it work in python3 ? 

i have two more question:
do you mind explaining what is ret_buf for? and what is the for loop at line 30 in t.py? it feels like it is inferring the same image 10 times? or am i wrong ?

thanks in advance :)

**Comment by mosheliv** [comment]
Ret_buf is just where the string with the results is stored. Yes, it is
inferring same image 10 times for timing

**Comment by IbrahimBond** [comment]
okay thanks a bunch. i am closing this issue :)
