### ISSUE TITLE
No Yolo App in Deepstream Reference Apps

### ISSUE THREAD

**Issue by ghost** [mosheliv/tensortrt-yolo-python-api#6]
I think they updated the [deepstream reference apps repo]( https://github.com/NVIDIA-AI-IOT/deepstream_reference_apps) there is no directory called "yolo" in it.

**Comment by ghost** [comment]
I found the Yolo app in another branch named "restructure" in that repo. You may want to update your readme.

**Comment by mosheliv** [comment]
Thanks, will do that

**Comment by ghost** [comment]
Plus I got `error:'CV_LOAD_IMAGE_COLOR' was not declared in this scope` while making the plugin in deepstream_reference_apps/yolo/lib/ds_image.cpp. And solved it by replacing  'CV_LOAD_IMAGE_COLOR' with 'cv::IMREAD_COLOR' in the mentioned cpp file.
